#=================================================
# Description: Generate Rule Provider for Clash
# Script by helmiau.com
# https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/'
# Run setiap 2 jam sekali
# curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/README.md | grep "blackmatrix7/ios_rule_script/tree/master/rule/Clash" | sed -e 's/ //g' -e 's/|/\n/g' -e 's#https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash/#rule_name: #iIg' -e 's#(#bukaan#g' -e 's#)##g' | sed '/^[[:space:]]*$/d' | sed 's/^.*\(rule_name.*\).*$/\1/' | sed 's#rule_name#          - rule_name#g' > include-rule.yaml
# Run setiap 2 jam sekali
#=================================================

name: Helmi STDIIS README Generator

on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 15 * * *
#  watch:
#    types: started

#env:
#  SUMBER: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/${{ matrix.rule_name }}/${{ matrix.rule_name }}.yaml
#  TZ: Asia/Jakarta

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Generate current time
        id: waktu
        run: |
          echo "::set-output name=waktu::$(date +'%Y-%m-%d_T%H:%M:%S')"

      - name: Generate latest README.md file
        id: generate
        run: |
          # echo -e '==== View README Before Update'
          # cat README.md
          # echo -e '==== View README After Update'
          [ -e README.md ] && rm README.md
          [ -e halaman/README.md ] && rm halaman/README.md
          # ls
          mv halaman/HEADER.md README.md
          cat halaman/DAFTARISI.md >> README.md
          cat halaman/AKADEMIK.md >> README.md
          cat halaman/AS1.md >> README.md
          cat halaman/AS2.md >> README.md
          cat halaman/AS3.md >> README.md
          cat halaman/AS4.md >> README.md
          cat halaman/AS5.md >> README.md
          cat halaman/AS6.md >> README.md
          cat halaman/AS7.md >> README.md
          cat halaman/AS8.md >> README.md
          cat halaman/IH1.md >> README.md
          cat halaman/IH2.md >> README.md
          cat halaman/IH3.md >> README.md
          cat halaman/IH4.md >> README.md
          cat halaman/IH5.md >> README.md
          cat halaman/IH6.md >> README.md
          cat halaman/IH7.md >> README.md
          cat halaman/IH8.md >> README.md
          cat halaman/ILA.md >> README.md
          cat halaman/ILB.md >> README.md
          cat halaman/TAHFIZ.md >> README.md
          cat halaman/TOAFL.md >> README.md
          cat halaman/LAIN.md >> README.md
          echo -e "diperbarui pada : ${{ steps.waktu.outputs.waktu }}" >> README.md
          cat halaman/FOOTER.md >> README.md
          # ls -R
          # cat README.md
          # echo -e "==== View README After Update END"

      - name: Delete Older Releases and Tags
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 0
          delete_tags: true
          delete_tag_pattern: stdiisj

      - name: Waiting 20 secs for deleting releases
        id: tunggu
        run: |
          sleep 20
          echo "::set-output name=status::success"

      - name: Upload Updates to GitHub Actions
        if: steps.tunggu.outputs.status == 'success' && !cancelled()
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: README-STDIIS
          tag_name: stdiisj
          draft: false
          prerelease: false
          files: "README.md"
          body: "diperbarui pada : ${{ steps.waktu.outputs.waktu }}"
          
      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
